---
- hosts: all
  become_user: root
  become: yes
  vars:
    centos7: "{{ ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7' }}"
    pip_install_packages:
      - name: pip
        state: latest
      - name: cryptography
      - name: pyOpenSSL

    pre_tasks:
      - name: Set vars for Cent OS backward compatibility
        set_fact:
          pip_package: python3-pip
          pip_install_packages:
            - name: cryptography
              version: "3.3"
            - name: pyOpenSSL
        when: centos7

  tasks:
    - name: Generate OpenStack key
      block:
        - set_fact:
            key_name: "{{ public_ipv4_address | replace('.','-') }}-xOpera"
            ssh_path: "/root/.ssh/"
        - file:
            path: "{{ ssh_path }}"
            state: directory
        - openssl_privatekey:
            path: "{{ ssh_path }}{{ key_name }}"
            size: 4096
        - openssl_publickey:
            path: "{{ ssh_path }}{{ key_name }}.pubk"
            format: OpenSSH
            privatekey_path: "{{ ssh_path }}{{ key_name }}"
        - slurp:
            src: "{{ ssh_path }}{{ key_name }}.pubk"
          register: key
        - authorized_key:
            user: "{{ ansible_user }}"
            state: present
            key: '{{ key.content | b64decode }}'

  roles:
    - role: geerlingguy.repo-epel
      when: ansible_distribution == "CentOS"
    - role: geerlingguy.pip