---
- hosts: all
  become_user: root
  become: yes

  vars:
    centos7: "{{ ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7' }}"
    pip_install_packages:
      - name: docker
    
  pre_tasks:
    - name: update cache
      package:
        update_cache: yes
    - name: Set vars for Cent OS backward compatibility
      set_fact:
        docker_package: "docker-ce-19.03.5-3.el7"
        pip_package: python3-pip
        pip_install_packages:
          - name: websocket-client
            version: "0.59.0"
          - name: docker
            version: "4.4.4"
      when: centos7

  tasks:
    - name: Set attributes
      set_stats:
        data:
          public_address: "{{ host_public_address }}"
          username: "{{ ansible_user }}"
    - name: Configure the docker mtu for OpenStack and restart docker host
      block:
        - lineinfile:
            path: /etc/docker/daemon.json
            line: "{\"mtu\": 1450}"
            create: yes
        - service:
            name: docker
            state: restarted

  roles:
    - role: geerlingguy.repo-epel
      when: ansible_distribution == "CentOS"
    - role: geerlingguy.pip
    - role: geerlingguy.docker
